config/routes.rb
RecipeBook::Application.routes.draw do
  resources :gadgets

  root :to => 'welcome#index'
  resources :ingredients

  resources :cookbooks

  resources :recipes

  

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  has_many :recipe_to_cookbook_relationship, :class_name => 'RecipeToCookbookRelationship'
  has_many :cookbooks, through: :recipe_to_cookbook_relationship

  has_many :ingredient_to_recipe_relationship, :class_name => 'IngredientToRecipeRelationship'
  has_many :ingredients, through: :ingredient_to_recipe_relationship

  has_many :gadget_to_recipe_relationship
  has_many :gadgets, through: :gadget_to_recipe_relationship

  def self.search(search)
    if search
      find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
    else
      find(:all)
    end
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.search(params[:search])
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
    @ingredients = Ingredient.all.collect { |p| [p.name, p.id] }
    @gadgets = Gadget.all.collect { |p| [p.name, p.id] }
  end

  # GET /recipes/1/edit
  def edit
    @ingredients = Ingredient.all.collect { |p| [p.name, p.id] }
    @gadgets = Gadget.all.collect { |p| [p.name, p.id] }
  end

  # POST /recipes
  # POST /recipes.json
  def create

    @recipe = Recipe.new(recipe_params)

    params[:recipe][:ingredients].each do |ingredient_id|
      next if ingredient_id.to_i == 0
      ingredient = Ingredient.find(ingredient_id.to_i)
      @recipe.ingredients << ingredient
    end

    params[:recipe][:gadgets].each do |gadget_id|
      next if gadget_id.to_i == 0
      gadget = Gadget.find(gadget_id.to_i)
      @recipe.gadgets << gadget
    end

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render action: 'show', status: :created, location: @recipe }
      else
        format.html { render action: 'new' }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)

      params[:recipe][:ingredients].each do |ingredient_id|
        next if ingredient_id.to_i == 0

      ingredient = Ingredient.find(ingredient_id.to_i)

      @recipe.ingredients << ingredient
    end

        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:name, :vegetarian, :process, :ingredients => {})
    end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_for(@recipe) do |f| %>
  <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% @recipe.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <br>
  <div class="field">
    <%= f.label :vegetarian %><br>
    <%= f.check_box :vegetarian %>
  </div>
  <br>
  <div class="field">
    <%= f.label :process %><br>
    <%= f.text_area :process %>
  </div>
  <br>
  <div class="field">
    <%= f.label :ingredients %><br>
    <%= f.select(:ingredients, @ingredients, {}, {:multiple => true}) %>
  </div>
  <br>
  <div class="field">
    <%= f.label :gadgets %><br>
    <%= f.select(:gadgets, @gadgets, {}, {:multiple => true}) %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render 'form' %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<h1>Listing recipes</h1>

<%= form_tag recipes_path, :method => 'get' do %>
<p>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Search", :name => nil %>
</p>
<% end %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Vegetarian</th>
      <th>Process</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @recipes.each do |recipe| %>
      <tr>
        <td><%= recipe.name %></td>
        <td><%= recipe.vegetarian %></td>
        <td><%= recipe.process %></td>
        <td><%= link_to 'Show', recipe %></td>
        <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
        <td><%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recipe', new_recipe_path %>

app/views/recipes/new.html.erb
<h1>New recipe</h1>

<%= render 'form' %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @recipe.name %>
</p>

<p>
  <strong>Vegetarian:</strong>
  <%= @recipe.vegetarian %>
</p>

<p>
  <strong>Process:</strong>
  <ul>
    <li><%= @recipe.process %></li>
  </ul>
</p>

<p>
  <strong>Ingredients:</strong>
</p>

	<% @recipe.ingredients.each do |ingredient| %>
     <%= link_to ingredient.name, ingredient_path(ingredient.id) %>
     <br>
  <% end %>

<p>
  <strong>Gadgets:</strong>
</p>

  <% @recipe.gadgets.each do |gadget| %>
     <%= link_to gadget.name, gadget_path(gadget.id) %>
     <br>
  <% end %>

<p>
  <strong>Found in these cookbooks:</strong>
</p>
  <% @recipe.cookbooks.each do |cookbook| %>
     <%= link_to cookbook.name, cookbook_path(cookbook.id) %>
  
     <br>
  <% end %>
<br>
<br>
<br>
<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %>