config/routes.rb
RecipeBook::Application.routes.draw do
  resources :gadgets

  root :to => 'welcome#index'
  resources :ingredients

  resources :cookbooks

  resources :recipes

  

end

app/models/gadget.rb
class Gadget < ActiveRecord::Base
  has_many :gadget_to_recipe_relationship
  has_many :recipes, through: :gadget_to_recipe_relationship

   def self.search(search)
    if search
      find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
    else
      find(:all)
    end
  end
end

app/controllers/gadgets_controller.rb
class GadgetsController < ApplicationController
  before_action :set_gadget, only: [:show, :edit, :update, :destroy]

  # GET /gadgets
  # GET /gadgets.json
  def index
    @gadgets = Gadget.search(params[:search])
  end

  # GET /gadgets/1
  # GET /gadgets/1.json
  def show
  end

  # GET /gadgets/new
  def new
    @gadget = Gadget.new
  end

  # GET /gadgets/1/edit
  def edit
  end

  # POST /gadgets
  # POST /gadgets.json
  def create
    @gadget = Gadget.new(gadget_params)

    respond_to do |format|
      if @gadget.save
        format.html { redirect_to @gadget, notice: 'Gadget was successfully created.' }
        format.json { render action: 'show', status: :created, location: @gadget }
      else
        format.html { render action: 'new' }
        format.json { render json: @gadget.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gadgets/1
  # PATCH/PUT /gadgets/1.json
  def update
    respond_to do |format|
      if @gadget.update(gadget_params)
        format.html { redirect_to @gadget, notice: 'Gadget was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @gadget.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gadgets/1
  # DELETE /gadgets/1.json
  def destroy
    @gadget.destroy
    respond_to do |format|
      format.html { redirect_to gadgets_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gadget
      @gadget = Gadget.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gadget_params
      params.require(:gadget).permit(:name, :purpose)
    end
end

app/helpers/gadgets_helper.rb
module GadgetsHelper
end

app/views/gadgets/_form.html.erb
<%= form_for(@gadget) do |f| %>
  <% if @gadget.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gadget.errors.count, "error") %> prohibited this gadget from being saved:</h2>

      <ul>
      <% @gadget.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :purpose %><br>
    <%= f.text_area :purpose %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gadgets/edit.html.erb
<h1>Editing gadget</h1>

<%= render 'form' %>

<%= link_to 'Show', @gadget %> |
<%= link_to 'Back', gadgets_path %>

app/views/gadgets/index.html.erb
<h1>Listing gadgets</h1>

<%= form_tag gadgets_path, :method => 'get' do %>
<p>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Search", :name => nil %>
</p>
<% end %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Purpose</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @gadgets.each do |gadget| %>
      <tr>
        <td><%= gadget.name %></td>
        <td><%= gadget.purpose %></td>
        <td><%= link_to 'Show', gadget %></td>
        <td><%= link_to 'Edit', edit_gadget_path(gadget) %></td>
        <td><%= link_to 'Destroy', gadget, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gadget', new_gadget_path %>

app/views/gadgets/new.html.erb
<h1>New gadget</h1>

<%= render 'form' %>

<%= link_to 'Back', gadgets_path %>

app/views/gadgets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @gadget.name %>
</p>

<p>
  <strong>Purpose:</strong>
  <%= @gadget.purpose %>
</p>

<p>
  <strong>Used in these recipes:</strong>
</p>

  <% @gadget.recipes.each do |recipe| %>
     <%= link_to recipe.name, recipe_path(recipe.id) %>
     <br>
  <% end %>
<br>
<br>
<br>
<%= link_to 'Edit', edit_gadget_path(@gadget) %> |
<%= link_to 'Back', gadgets_path %>