config/routes.rb
RecipeBook::Application.routes.draw do
  resources :gadgets

  root :to => 'welcome#index'
  resources :ingredients

  resources :cookbooks

  resources :recipes

  

end

app/models/cookbook.rb
class Cookbook < ActiveRecord::Base
  has_many :recipe_to_cookbook_relationship, :class_name => 'RecipeToCookbookRelationship'
  has_many :recipes, through: :recipe_to_cookbook_relationship

   def self.search(search)
    if search
      find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
    else
      find(:all)
    end
  end
end

app/controllers/cookbooks_controller.rb
class CookbooksController < ApplicationController
  before_action :set_cookbook, only: [:show, :edit, :update, :destroy]

  # GET /cookbooks
  # GET /cookbooks.json
  def index
    @cookbooks = Cookbook.search(params[:search])
  end

  # GET /cookbooks/1
  # GET /cookbooks/1.json
  def show
  end

  # GET /cookbooks/new
  def new
    @cookbook = Cookbook.new
    @recipes = Recipe.all.collect { |p| [p.name, p.id] }
  end

  # GET /cookbooks/1/edit
  def edit
    @recipes = Recipe.all.collect { |p| [p.name, p.id] }
  end

  # POST /cookbooks
  # POST /cookbooks.json
  def create
    @cookbook = Cookbook.new(cookbook_params)

    params[:cookbook][:recipes].each do |recipe_id|
      next if recipe_id.to_i == 0
      recipe = Recipe.find(recipe_id.to_i)
      @cookbook.recipes << recipe
    end

    respond_to do |format|
      if @cookbook.save
        format.html { redirect_to @cookbook, notice: 'Cookbook was successfully created.' }
        format.json { render action: 'show', status: :created, location: @cookbook }
      else
        format.html { render action: 'new' }
        format.json { render json: @cookbook.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cookbooks/1
  # PATCH/PUT /cookbooks/1.json
  def update

    respond_to do |format|
      if @cookbook.update(cookbook_params)
        
        params[:cookbook][:recipes].each do |recipe_id|
          next if recipe_id.to_i == 0
          recipe = Recipe.find(recipe_id.to_i)
          @cookbook.recipes << recipe
        end

        format.html { redirect_to @cookbook, notice: 'Cookbook was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @cookbook.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cookbooks/1
  # DELETE /cookbooks/1.json
  def destroy
    @cookbook.destroy
    respond_to do |format|
      format.html { redirect_to cookbooks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cookbook
      @cookbook = Cookbook.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cookbook_params
      params.require(:cookbook).permit(:name)
    end
end

app/helpers/cookbooks_helper.rb
module CookbooksHelper
end

app/views/cookbooks/_form.html.erb
<%= form_for(@cookbook) do |f| %>
  <% if @cookbook.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cookbook.errors.count, "error") %> prohibited this cookbook from being saved:</h2>

      <ul>
      <% @cookbook.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <p>
    <strong>Recipes:</strong>
  </p>
    <%= f.select(:recipes, @recipes, {}, {:multiple => true}) %>
  <p>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cookbooks/edit.html.erb
<h1>Editing cookbook</h1>

<%= render 'form' %>

<%= link_to 'Show', @cookbook %> |
<%= link_to 'Back', cookbooks_path %>

app/views/cookbooks/index.html.erb
<h1>Listing cookbooks</h1>

<%= form_tag cookbooks_path, :method => 'get' do %>
<p>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Search", :name => nil %>
</p>
<% end %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @cookbooks.each do |cookbook| %>
      <tr>
        <td><%= cookbook.name %></td>
        <td><%= link_to 'Show', cookbook %></td>
        <td><%= link_to 'Edit', edit_cookbook_path(cookbook) %></td>
        <td><%= link_to 'Destroy', cookbook, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cookbook', new_cookbook_path %>

app/views/cookbooks/new.html.erb
<h1>New cookbook</h1>

<%= render 'form' %>

<%= link_to 'Back', cookbooks_path %>

app/views/cookbooks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cookbook.name %>
</p>

<br>
<br>
<br>

<p> 
  <strong>Recipes:</strong>
</p>
	<% @cookbook.recipes.each do |recipe| %>
     <%= link_to recipe.name, recipe_path(recipe.id) %>
     <br>
  <% end %>

<br>
<br>
<br>
<%= link_to 'Edit', edit_cookbook_path(@cookbook) %> |
<%= link_to 'Back', cookbooks_path %>